/*
 * generated by github.com/calgagi/cp_gen
 * file: A.cpp
 * time: Fri Dec 18 21:02:10 2020
 */

#include<bits/stdc++.h>

using namespace std;

typedef long long ll;
typedef long double ld;

vector<string> received;
vector<string> rules;

int num_rules;

struct Node {
    vector<vector<int>> reps;
    char match = ' ';
};

vector<Node> rule_to_node(200);

// we know parsing is doing correctly from diff
void parse_rule(string& s) {
    int colon = s.find(":");
    int idx = stoi(s.substr(0, colon));

    Node& node = rule_to_node[idx];
    
    int i = colon+2;
    if (s[i] == '\"') {
        node.match = s[i+1];
    }
    else {
        vector<int> idxs;
        string num = "";
        for (; i < (int) s.length(); i++) {
            if (s[i] == '|') {
                node.reps.push_back(idxs);
                idxs.clear();
                // get rid of space
                i++;
            }
            else if (s[i] == ' ') {
                idxs.push_back(stoi(num)); 
                num = "";
            }
            else {
                num += s[i];
            }
        }
        if (num != "") {
            idxs.push_back(stoi(num));
        }
        if (!idxs.empty()) {
            node.reps.push_back(idxs);
        }
    }

    assert((node.match != ' ') ^ (node.reps.size() != 0));
    return;
}

string grab_regex(int rule, int depth) {
    if (depth == 0) {
        return "";
    }
    const Node& node = rule_to_node[rule];
    if (node.match != ' ') {
        return string(1, node.match);
    }
    string ans = "(";
    for (const vector<int>& rep : node.reps) {
        if (ans != "(" && ans.back() != '|') {
            ans += "|";
        }
        for (const int& x : rep) {
            ans += grab_regex(x, depth - 1);
        }
    }
    ans = ans == "(" ? "" : ans + ")";

    return ans;
}

void solve() {
    bool mode = false;
    string line;
    while (getline(cin, line)) {
        if (line == "") {
            mode = true;
        }
        if (!mode) rules.push_back(line);
        else if (line != "") received.push_back(line);
    }
    
    num_rules = rules.size();
    for (string& s : rules) {
        parse_rule(s);
    }

    string r = grab_regex(0, 22);
    cout << r << endl;

    int ans = 0;
    for (string& msg : received) {
        if (regex_match(msg, regex(r))) {
            ans++;
        }
    }

    cout << ans << endl;

    return;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int num_tests = 1;
    /* cin >> num_tests; */
    for (int i = 0; i < num_tests; i++) {
        solve();
    }

    return 0;
}
