/*
 * generated by github.com/calgagi/cp_gen
 * file: A.cpp
 * time: Sat Dec 11 20:59:33 2021
 */

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
typedef long double ld;

namespace cp {

class parser {
public:
    string input = "";
    int idx = 0, len = 0;

    parser() {
        string line;
        while (getline(cin, line)) input += (line += '\n');
        len = input.length();
    }

    parser(string filename) {
        fstream f(filename, ios_base::in);
        string line;
        if (f.is_open()) while (getline(f, line)) input += (line += '\n');
        len = input.length();
    }

    bool empty() {
        return idx >= len;
    } 

    ll get_ll() {
        string num = "";
        if (idx < len && input[idx] == '-') num += input[idx++];
        while (idx < len && input[idx] >= '0' && input[idx] <= '9') num += input[idx++];
        return stoll(num);
    }

    char get_char() {
        return (idx < len ? input[idx++] : ' ');
    }

    void ws() {
        while (idx < len && input[idx] == ' ' || input[idx] == '\n' || input[idx] == '\t') idx++;
    }

    string get_word() {
        string word = "";
        while (idx < len && ((input[idx] >= 'a' && input[idx] <= 'z') || (input[idx] >= 'A' && input[idx] <= 'Z'))) word += input[idx++];
        return word;
    }

    string get_until(char deliminator = ' ') {
        string res = "";
        while (idx < len && input[idx] != deliminator && input[idx] != '\n') res += input[idx++];
        return res;
    }
};


template <class F>
struct _rlamb {
    F f;
    template <class... Args>
    decltype(auto) operator()(Args&&... args) const { return f(*this, forward<Args>(args)...); }
};

template <class F>
_rlamb<decay_t<F>> rlamb(F&& f) { return { forward<F>(f) }; }

}

/* ===== BEGIN USER CODE ===== */

int main() {
    ios_base::sync_with_stdio(0); cin.tie(0);
    mt19937 rng(chrono::steady_clock::now().time_since_epoch().count());

    cp::parser p;
    unordered_map<string, int> id;
    int n = 0;
    vector<vector<int>> graph;
    vector<bool> small;

    while (!p.empty()) {
        string u = p.get_until('-');
        p.get_char();
        string v = p.get_until();

        if (id.find(u) == id.end()) {
            id[u] = n++;
            graph.push_back(vector<int>());
            small.push_back(!isupper(u[0]));
        }

        if (id.find(v) == id.end()) {
            id[v] = n++;
            graph.push_back(vector<int>());
            small.push_back(!isupper(v[0]));
        }

        graph[id[u]].push_back(id[v]);
        graph[id[v]].push_back(id[u]);
        p.ws();
    }

    vector<int> visited(n, 0);
    bool used = false;
    int twice_allow = -1;

    auto dfs = cp::rlamb([&](auto&& dfs, const int& cur) -> ll {
        if (cur == id["end"] && (twice_allow == -1 || visited[twice_allow] == 2)) {
            return 1;
        }
        if (cur == id["end"]) {
            return 0;
        }
        if (visited[cur] >= 1 && small[cur]) {
            if (cur != twice_allow) {
                return 0;
            }
            if (visited[cur] == 2) {
                return 0;
            }
        }
        visited[cur]++;
        ll res = 0;
        for (const int& v : graph[cur]) {
            res += dfs(v);
        }
        if (visited[cur] == 2 && small[cur]) {
            used = false;
        }
        visited[cur]--;
        return res;
    });

    // singles
    ll ans = dfs(id["start"]);
    cout << ans << endl;

    for (int i = 0; i < n; i++) {
        if (small[i] && i != id["start"]) {
            twice_allow = i;
            ans += dfs(id["start"]);
        }
    }

    cout << ans << endl;

    return 0;
}
