/*
 * generated by github.com/calgagi/cp_gen
 * file: A.cpp
 * time: Tue Dec 29 00:27:41 2020
 */

#include<bits/stdc++.h>

using namespace std;

typedef long long ll;
typedef long double ld;

const ll MOD = 20201227;

ll loop_size(ll x, ll y) {
    ll ans = 0, cur = 1;

    while (cur != x) {
        ans++;
        cur *= y;
        cur %= MOD;
    }

    return ans;
}

ll modpow(ll b, ll e) {
    ll ans = 1;
    while (e) {
        if (e & 1LL) {
            ans *= b;
            ans %= MOD;
        }
        b *= b;
        b %= MOD;
        e >>= 1;
    }
    return ans;
}

void solve() {
    ll a, b;
    cin >> a >> b;

    ll la = loop_size(a, 7), lb = loop_size(b, 7);

    cout << modpow(b, la) << endl;
    cout << modpow(a, lb) << endl;

    return;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int num_tests = 1;
    /* cin >> num_tests; */
    for (int i = 0; i < num_tests; i++) {
        solve();
    }

    return 0;
}
