/*
 * generated by github.com/calgagi/cp_gen
 * file: A.cpp
 * time: Wed Dec  9 21:01:28 2020
 */

#include<bits/stdc++.h>

using namespace std;

typedef long long ll;
typedef long double ld;

void solve() {
    int x;
    vector<int> in;
    while (cin >> x) {
        in.push_back(x);
    }

    int n = in.size();
    in.push_back(0);
    sort(in.begin(), in.end());
    vector<ll> dp(n+1, 0);
    dp[0] = 1;
    for (int i = 1; i <= n; i++) {
        for (int j = 1; j <= 3 && i-j >= 0; j++) {
            if (in[i] - in[i-j] <= 3) {
                dp[i] += dp[i-j];
            }
        }
    }

    cout << dp[n] << endl;

    return;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int num_tests = 1;
    /* cin >> num_tests; */
    for (int i = 0; i < num_tests; i++) {
        solve();
    }

    return 0;
}
