/*
 * generated by github.com/calgagi/cp_gen
 * file: A.cpp
 * time: Tue Dec 22 22:30:14 2020
 */

#include<bits/stdc++.h>

using namespace std;

typedef long long ll;
typedef long double ld;

const int TURNS = 100, PICK = 3, NODES = 9;

struct Node {
    Node* next;
    int val;
    Node(int v) : val(v) {};
};

Node* head = NULL;

void print_list(Node* cur) {
    for (int i = 0; i < NODES; i++) {
        cout << cur->val; 
        cur = cur->next;
    }
    cout << endl;
}

void solve() {
    string s;
    cin >> s;

    head = new Node(s[0] - '0');
    Node* it = head;
    for (int i = 1; i < (int) s.length(); i++) {
        it->next = new Node(s[i] - '0');
        it = it->next;
    }
    it->next = head;
    
    Node* cur = head;
    for (int turn = 0; turn < TURNS; turn++) {
        // pickup stores PICK nodes
        Node* pickup = cur->next;
        it = cur->next;
        cur->next = NULL;
        for (int p = 0; p < PICK-1; p++) {
            it = it->next;
        }
        // it is at end of PICK
        cur->next = it->next;
        it->next = NULL;
        // successfully picked up PICK nodes
        for (int search = ((cur->val - 2 + NODES) % NODES) + 1; ; search = ((search - 2 + NODES) % NODES) + 1) {
            int go = NODES - PICK;
            Node* it2 = cur;
            while (go-- && it2->val != search) {
                it2 = it2->next;
            }
            if (it2->val == search) {
                it->next = it2->next;
                it2->next = pickup;
                break;
            }
        } 
        cur = cur->next;
    }

    for (int i = 0; i < NODES; i++) {
        if (cur->val == 1) {
            print_list(cur);
        }
        cur = cur->next;
    }

    return;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int num_tests = 1;
    /* cin >> num_tests; */
    for (int i = 0; i < num_tests; i++) {
        solve();
    }

    return 0;
}
