/*
 * generated by github.com/calgagi/cp_gen
 * file: A.cpp
 * time: Fri Dec  4 21:01:57 2020
 */

#include<bits/stdc++.h>

using namespace std;

typedef long long ll;
typedef long double ld;

void solve() {
    vector<string> seats;
    string in;
    while (cin >> in) {
        seats.push_back(in);
    }

    vector<bool> used(10000, false);
    int ans = 0;
    for (string& s : seats) {
        // row
        int cur = 0;
        for (int i = 0; i < 7; i++) {
            if (s[i] == 'B') {
                cur += (1 << (6 - i));
            }
        }
        cur *= 8;
        // col
        for (int i = 7, j = 0; i < 10; i++, j++) {
            if (s[i] == 'R') {
                cur += (1 << (2 - j));
            }
        }
        used[cur] = true;
    }
    
    for (int i = 1; i < 9999; i++) {
        if (used[i-1] && used[i+1] && !used[i]) {
            cout << i << endl;
        }
    }

    return;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int num_tests = 1;
    /* cin >> num_tests; */
    for (int i = 0; i < num_tests; i++) {
        solve();
    }

    return 0;
}
