/*
 * generated by github.com/calgagi/cp_gen
 * file: A.cpp
 * time: Thu Dec 10 21:06:51 2020
 */

#include<bits/stdc++.h>

using namespace std;

typedef long long ll;
typedef long double ld;

vector<pair<int,int>> dirs = {{1,0}, {-1,0}, {1,1}, {-1,-1}, {0,1}, {-1, 1}, {1,-1}, {0,-1}};

void solve() {
    vector<string> in;
    string line;
    while (cin >> line) {
        in.push_back(line);
    }

    int n = in.size(), m = in[0].length();
    int changed;
    do {
        vector<string> new_in = in;
        changed = 0;
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < m; j++) {
                int adj = 0;
                for (pair<int,int>& dir : dirs) {
                    int r = dir.first + i, c = dir.second + j;
                    if (r >= 0 && r < n && c >= 0 && c < m) {
                        adj += in[r][c] == '#';
                    }
                }
                if (in[i][j] == 'L' && adj == 0) {
                    new_in[i][j] = '#';
                    cout << "HERE" << endl;
                    changed++;
                } 
                else if (in[i][j] == '#' && adj >= 4) {
                    new_in[i][j] = 'L';
                    changed++;
                }
                cout << new_in[i][j];
            }
            cout << endl;
        }
        in = new_in;
        cout << changed << endl;
    } while (changed);

    int ans = 0;
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < m; j++) {
            cout << in[i][j];
            ans += in[i][j] == '#';
        }
        cout << endl;
    }
    cout << ans << endl;
            
    
    return;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int num_tests = 1;
    /* cin >> num_tests; */
    for (int i = 0; i < num_tests; i++) {
        solve();
    }

    return 0;
}
