/*
 * generated by github.com/calgagi/cp_gen
 * file: A.cpp
 * time: Thu Dec 17 21:00:58 2020
 */

#include<bits/stdc++.h>

using namespace std;

typedef long long ll;
typedef long double ld;

void perform_op(ll& ans, char op, ll other) {
    if (op == '*') {
        ans *= other;
    } 
    else if (op == '+') {
        ans += other;
    }
}

ll go(int& i, const string& s) {
    ll ans = 0;
    string num = "";
    char op = '+';
    for (; i < (int) s.length(); i++) {
        if (s[i] == '(') {
            i++;
            perform_op(ans, op, go(i, s));
        }
        else if (s[i] == ')') {
            break;
        }
        else if (s[i] == '*' || s[i] == '+') {
            if (num != "") {
                perform_op(ans, op, stoll(num));
                num = "";
            }
            op = s[i];
        }
        else {
            num += s[i];
        }
    }
    if (num != "") {
        perform_op(ans, op, stoll(num));
    }
    return ans;
}

void solve() {
    ll ans = 0;
    string line;
    while (getline(cin, line)) {
        // get rid of spaces
        string new_line = "";
        for (char& c : line) {
            if (c != ' ') {
                new_line += c;
            }
        }
        new_line.push_back(')');
        new_line.insert(new_line.begin(), '(');
        cout << new_line << endl;

        int x = 0;
        ll a = go(x, new_line);

        cout << a << endl;
        ans += a;
    }
    cout << ans << endl;

    return;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int num_tests = 1;
    /* cin >> num_tests; */
    for (int i = 0; i < num_tests; i++) {
        solve();
    }

    return 0;
}
