/*
 * generated by github.com/calgagi/cp_gen
 * file: A.cpp
 * time: Tue Dec  1 21:17:41 2020
 */

#include<bits/stdc++.h>

using namespace std;

typedef long long ll;
typedef long double ld;

void solve() {
    set<int> seen;
    int cur;
    while (cin >> cur) {
        if (seen.count(2020 - cur)) {
            cout << cur * (2020 - cur) << endl;
        }
        seen.insert(cur);
    }

    return;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int num_tests = 1;
    // cin >> num_tests;
    for (int i = 0; i < num_tests; i++) {
        solve();
    }

    return 0;
}
