/*
 * generated by github.com/calgagi/cp_gen
 * file: A.cpp
 * time: Mon Dec 21 20:44:53 2020
 */

#include<bits/stdc++.h>

using namespace std;

typedef long long ll;
typedef long double ld;

map<string, int> str_to_id;
map<int, string> id_to_str;
int cur_id = 1;

vector<vector<int>> candidates;
vector<bool> used;
vector<int> ans;

struct Food {
    vector<int> ingredients;
    vector<int> allergens;
};
vector<Food> foods;

string get_until_space(const string& a, int& i) {
    string s;
    for (; i < (int) a.length() && a[i] != ' '; i++) {
        s += a[i];
    }
    return s;
}

void parse(string& s) {
    Food f;
    bool mode = false;

    for (int i = 0; i < (int) s.length(); i++) {
        if (!mode) {
            string in = get_until_space(s, i);
            if (in == "(contains") {
                mode = true;
                continue;
            }
            if (str_to_id[in] == 0) {
                str_to_id[in] = cur_id++;
                id_to_str[cur_id-1] = in;
            }
            f.ingredients.push_back(str_to_id[in]);
        }
        else {
            string al = get_until_space(s, i);
            al.pop_back();
            if (str_to_id[al] == 0) {
                str_to_id[al] = cur_id++;
                id_to_str[cur_id-1] = al;
            }
            f.allergens.push_back(str_to_id[al]);
        }
    }

    foods.push_back(f);
    return;
}

bool match(int i) {
    if (i >= cur_id) {
        return true;
    }
    if (candidates[i].empty()) {
        return match(i+1);
    }

    for (int& candidate : candidates[i]) {
        if (!used[candidate]) {
            used[candidate] = true;
            ans[i] = candidate;
            if (match(i+1)) {
                return true;
            }
            used[candidate] = false;
            ans[i] = 0;
        }
    }

    return false;
}

void part2() {
    // allergen -> ingredient -> count
    map<int, map<int,int>> cnt;
    // allergen -> count
    map<int, int> al_cnt;
    // ingredient -> count
    map<int, int> in_cnt;

    for (Food& f : foods) {
        for (int& in : f.ingredients) {
            in_cnt[in]++;
        }
        for (int& al : f.allergens) {
            al_cnt[al]++;
            for (int& in : f.ingredients) {
                cnt[al][in]++; 
            }
        }
    }

    map<int, bool> bad;
    candidates.resize(cur_id);
    // for each allergen
    for (const pair<int, map<int,int>>& p : cnt) {
        int id = p.first;
        // for each ingredient that the allergen points to
        for (const pair<int,int>& in : p.second) {
            if (al_cnt[id] <= in.second) {
                candidates[id].push_back(in.first);
            }
        }
    }

    used.assign(cur_id, false);
    ans.assign(cur_id, 0);
    match(0);

    vector<pair<string,string>> x;
    for (int i = 0; i < cur_id; i++) {
        if (ans[i] != 0) {
            x.push_back({id_to_str[i], id_to_str[ans[i]]});
        }
    }

    sort(x.begin(), x.end());

    string to_print = "";
    for (const pair<string,string>& p : x) {
        to_print += p.second;
        to_print += ",";
    }
    to_print.pop_back();

    cout << to_print << endl;

    return;
}

void solve() {
    string line;
    while (getline(cin, line)) {
        parse(line);
    }

    part2();

    return;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int num_tests = 1;
    /* cin >> num_tests; */
    for (int i = 0; i < num_tests; i++) {
        solve();
    }

    return 0;
}
